#ifndef PDFMM_PDFVERSION_H
#define PDFMM_PDFVERSION_H

#define PDFMM_MAJOR PDFMM_VERSION_MAJOR
#define PDFMM_MINOR PDFMM_VERSION_MINOR
#define PDFMM_REVISION PDFMM_VERSION_PATCH

#define PDFMM_VERSION_STRING PDFMM_VERSION_STR

#endif // PDFMM_PDFVERSION_H
